name: TSMCxNYCU CD (GKE)

on:
  push:
    branches:
      - "main"
jobs:
  Dockerize:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@master
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: ""
          project_id: ""
          image_name: ""
  CommitHelm:
    name: Commit to HELM repo
    runs-on: ubuntu-latest
    needs: [Dockerize]
    steps:
      # You need to checkout to get the whole directory
      # cpina does not support copying files 
      - uses: actions/checkout@v3
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "src/"
          target-directory: "src/"
          target-branch: "main"
          destination-github-username: "gamerslouis"
          destination-repository-name: "cloudnative_helm_charts"
          user-email: alan890104@gmail.com