name: TSMCxNYCU CD (docker hub)

on:
  push:
    branches:
      - "dev"
jobs:
  Dockerize:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Notice that we should use docker-hub repo name as tags, but not github repo
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: waterso/tsmc-1:latest
  CommitHelm:
    name: Commit to HELM repo
    runs-on: ubuntu-latest
    needs: [Dockerize]
    steps:
      # You need to checkout to get the whole directory
      # cpina does not support copying files 
      - uses: actions/checkout@v3
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "src/"
          target-directory: "src/"
          target-branch: "main"
          destination-github-username: "gamerslouis"
          destination-repository-name: "cloudnative_helm_charts"
          user-email: alan890104@gmail.com